"""Contract linter: skill ↔ manifest ↔ schema ↔ tool consistency.

Catches the four classes of drift this codebase keeps regenerating:

  1. Artifact graph closure — every artifact consumed via `required_artifacts_in`
     must be produced by another stage in the same manifest.
  2. Schema coverage — every artifact that crosses a stage boundary must have
     a schema file on disk.
  3. Skill ↔ schema field references — when a skill mentions
     `<artifact>.<field.path>`, that path must resolve in the artifact schema
     (unless the schema sets additionalProperties: true at that level).
  4. Embedded JSON examples — fenced ```json blocks in skills that are
     explicitly tagged as a known artifact must validate against that schema.

The linter is intentionally narrow: it asserts only what is mechanically
checkable without false positives. Everything else stays in human review.
"""

from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path

import jsonschema
import pytest
import yaml

from tools.tool_registry import registry

REPO = Path(__file__).resolve().parents[2]
PIPELINE_DIR = REPO / "pipeline_defs"
SCHEMA_DIR = REPO / "schemas" / "artifacts"
SKILLS_DIR = REPO / "skills"


# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------


def all_pipelines() -> list[Path]:
    return sorted(PIPELINE_DIR.glob("*.yaml"))


def load_pipeline(path: Path) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def known_artifact_names() -> set[str]:
    return {p.stem.replace(".schema", "") for p in SCHEMA_DIR.glob("*.schema.json")}


def load_schema(name: str) -> dict | None:
    path = SCHEMA_DIR / f"{name}.schema.json"
    if not path.exists():
        return None
    return json.loads(path.read_text())


def collect_artifacts(manifest: dict) -> tuple[set[str], set[str]]:
    producers: set[str] = set()
    consumers: set[str] = set()
    for stage in manifest.get("stages", []):
        for unit in [stage, *(stage.get("sub_stages") or [])]:
            for a in unit.get("produces") or []:
                producers.add(a)
            for a in unit.get("required_artifacts_in") or []:
                consumers.add(a)
            for a in unit.get("optional_artifacts_in") or []:
                consumers.add(a)
    return producers, consumers


def _declared_stage_tools(stage: dict) -> dict[str, list[str]]:
    return {
        "required_tools": stage.get("required_tools") or [],
        "optional_tools": stage.get("optional_tools") or [],
        "fallback_tools": stage.get("fallback_tools") or [],
        "tools_available": stage.get("tools_available") or [],
    }


# ---------------------------------------------------------------------------
# Check 1: artifact graph closure
# ---------------------------------------------------------------------------

# Artifacts legitimately produced outside the pipeline stage graph.
# These appear in `required_artifacts_in` / `optional_artifacts_in` without
# a corresponding `produces:` declaration because they're external inputs
# generated by a meta-skill or utility before the pipeline starts. Each
# entry maps the artifact name to a one-line rationale so the exemption
# stays auditable.
EXTERNAL_INPUT_ARTIFACTS: dict[str, str] = {
    # Produced by lib/source_media_review.review_source_media() (a utility,
    # not a stage) when the user supplies media files. See skills/meta/
    # video-reference-analyst.md and skills/meta/reviewer.md:255-266.
    "source_media_review": "produced by lib/source_media_review utility before first planning stage",
    # The user's original natural-language brief — pre-pipeline input,
    # not a stage output. Distinct from research_brief (which IS a stage output).
    "brief": "user-supplied natural-language brief — pre-pipeline input",
    # Produced by the video-reference analysis workflow when the user provides
    # a reference video before normal pipeline planning begins.
    "video_analysis_brief": "produced by the video-reference analysis workflow before pipeline planning",
}


@pytest.mark.parametrize("pipeline_path", all_pipelines(), ids=lambda p: p.stem)
def test_artifact_graph_is_closed(pipeline_path: Path) -> None:
    """Every consumed artifact must be produced by some stage OR be an external input."""
    manifest = load_pipeline(pipeline_path)
    producers, consumers = collect_artifacts(manifest)
    orphans = consumers - producers - EXTERNAL_INPUT_ARTIFACTS.keys()
    assert not orphans, (
        f"Pipeline {pipeline_path.stem!r} consumes artifacts with no producer: "
        f"{sorted(orphans)}.\n"
        f"Either add a stage that produces them, remove them from "
        f"required_artifacts_in / optional_artifacts_in, or document them as "
        f"external inputs in EXTERNAL_INPUT_ARTIFACTS with a rationale."
    )


# ---------------------------------------------------------------------------
# Check 2: schema coverage for cross-stage artifacts
# ---------------------------------------------------------------------------

# Artifacts that intentionally have no schema (e.g., free-form intermediate
# state). Add to this set with a code comment explaining why, so the exemption
# stays auditable. Empty by default — every cross-stage artifact should have
# a schema unless explicitly justified.
SCHEMALESS_ARTIFACTS_ALLOWED: set[str] = set()


@pytest.mark.parametrize("pipeline_path", all_pipelines(), ids=lambda p: p.stem)
def test_cross_stage_artifacts_have_schemas(pipeline_path: Path) -> None:
    """If an artifact crosses a stage boundary, its schema must exist on disk."""
    manifest = load_pipeline(pipeline_path)
    producers, consumers = collect_artifacts(manifest)
    cross_stage = producers & consumers
    schemas = known_artifact_names()
    missing = {
        name
        for name in cross_stage
        if name not in schemas and name not in SCHEMALESS_ARTIFACTS_ALLOWED
    }
    assert not missing, (
        f"Pipeline {pipeline_path.stem!r} crosses stages with artifacts that have "
        f"no schema in schemas/artifacts/: {sorted(missing)}.\n"
        f"Add a <name>.schema.json file or document the exemption in "
        f"SCHEMALESS_ARTIFACTS_ALLOWED."
    )


# ---------------------------------------------------------------------------
# Check 2b: manifest tool declarations match the live registry
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("pipeline_path", all_pipelines(), ids=lambda p: p.stem)
def test_manifest_stage_tools_are_registered_and_callable(pipeline_path: Path) -> None:
    """Every stage tool reference must be registered and callable from tools_available."""
    registry.discover()
    known_tools = set(registry._tools)
    manifest = load_pipeline(pipeline_path)
    failures: list[str] = []

    for stage in manifest.get("stages", []):
        stage_name = stage.get("name", "<unnamed>")
        declared = _declared_stage_tools(stage)
        available = set(declared["tools_available"])

        for field, tools in declared.items():
            for tool_name in tools:
                if tool_name not in known_tools:
                    failures.append(f"{stage_name}: {field} references unknown tool {tool_name!r}")

        for field in ("required_tools", "optional_tools"):
            for tool_name in declared[field]:
                if tool_name not in available:
                    failures.append(
                        f"{stage_name}: {field} includes {tool_name!r} but tools_available omits it"
                    )

        for sub_stage in stage.get("sub_stages") or []:
            sub_name = sub_stage.get("name", "<unnamed>")
            for tool_name in sub_stage.get("tools_available") or []:
                if tool_name not in known_tools:
                    failures.append(
                        f"{stage_name}.{sub_name}: tools_available references unknown tool {tool_name!r}"
                    )

    for mode in manifest.get("production_modes") or []:
        mode_name = mode.get("name", "<unnamed>")
        for field in ("required_tools", "optional_tools"):
            for tool_name in mode.get(field) or []:
                if tool_name not in known_tools:
                    failures.append(
                        f"production_mode {mode_name}: {field} references unknown tool {tool_name!r}"
                    )

    reference_input = manifest.get("reference_input") or {}
    for tool_name in reference_input.get("analysis_tools") or []:
        if tool_name not in known_tools:
            failures.append(f"reference_input: analysis_tools references unknown tool {tool_name!r}")

    assert not failures, (
        f"Pipeline {pipeline_path.stem!r} has invalid tool declarations:\n  - "
        + "\n  - ".join(failures)
    )


def test_cinematic_research_does_not_require_unavailable_web_search_tools() -> None:
    """A stage with no registered search tool must not require web-search counts."""
    manifest = load_pipeline(PIPELINE_DIR / "cinematic.yaml")
    research_stage = next(stage for stage in manifest["stages"] if stage["name"] == "research")
    contract_text = "\n".join(research_stage.get("success_criteria") or [])
    director_text = (SKILLS_DIR / "pipelines" / "cinematic" / "research-director.md").read_text()

    assert research_stage.get("tools_available") == []
    assert "web search" not in contract_text.lower()
    assert "web search, web fetch" not in director_text.lower()
    assert "min searches" not in director_text.lower()


# ---------------------------------------------------------------------------
# Check 3: skill ↔ schema field references
# ---------------------------------------------------------------------------

# Pattern: artifact_name.field.path — restricted to lowercase snake_case to
# avoid matching CamelCase class references and English prose.
_FIELD_REF_RE = re.compile(r"\b([a-z][a-z0-9_]+)((?:\.[a-z][a-z0-9_]*)+)\b")

# Tokens that look like artifact references but are domain terms, file paths,
# or English prose. Excluded to keep the signal clean.
_NON_ARTIFACT_PREFIXES = {
    "skills",
    "tools",
    "lib",
    "tests",
    "schemas",
    "pipeline_defs",
    "projects",
    "music_library",
    "remotion_composer",
    "hyperframes",
    "pipelines",
    "audio",
    "video",
    "artifacts",
    "subtitles_ass",
    "subtitles_srt",
}

# Path segments that signal "this is a filename, not a schema field". When the
# first tail segment is one of these, drop the reference entirely — e.g.
# `script.schema.json`, `asset_manifest.yaml`, `render_report.json`.
_FILE_SUFFIX_FIRST_SEGMENTS = {"schema", "json", "yaml", "yml", "md", "py", "txt"}

# Python dict / object method names that appear after artifact-shaped variables
# in pseudocode blocks (e.g., `production_bible.get(...)`, `script.setdefault(...)`).
# These are not schema field references.
_PYTHON_DICT_METHODS = {
    "get",
    "setdefault",
    "pop",
    "popitem",
    "update",
    "keys",
    "values",
    "items",
    "copy",
    "clear",
    "fromkeys",
}


def _path_is_valid(schema: dict, path: tuple[str, ...]) -> bool:
    """Walk a dotted path through an object schema; return True if reachable.

    Lenient: returns True at any node where additionalProperties is not False
    (the schema does not lock unknown fields, so we cannot disprove the
    reference). Returns True on oneOf/anyOf/allOf/$ref nodes (out of scope
    for static walk).
    """
    cursor: dict | object = schema
    for part in path:
        if not isinstance(cursor, dict):
            return True
        if any(k in cursor for k in ("oneOf", "anyOf", "allOf", "$ref")):
            return True  # opaque; treat as pass
        # If the current node is an array, descend into items before continuing.
        if cursor.get("type") == "array" and isinstance(cursor.get("items"), dict):
            cursor = cursor["items"]
            if any(k in cursor for k in ("oneOf", "anyOf", "allOf", "$ref")):
                return True
        props = cursor.get("properties") or {}
        if part in props:
            cursor = props[part]
            continue
        if cursor.get("patternProperties") or cursor.get("additionalProperties") is True:
            return True
        if cursor.get("additionalProperties") in (None, {}):
            return True
        return False
    return True


# Inline code spans (`code`) and fenced code blocks ```...``` often contain
# Python module paths, file paths, and function-call syntax that look like
# artifact field references but aren't. Strip them before matching to keep
# the signal narrow to prose / non-code text.
_INLINE_CODE_RE = re.compile(r"`[^`\n]+`")
_FENCED_CODE_RE = re.compile(r"```[a-z0-9]*\n.*?\n```", re.DOTALL)


def _strip_code_spans(text: str) -> str:
    """Remove fenced code blocks and inline backtick spans from markdown text."""
    text = _FENCED_CODE_RE.sub("", text)
    text = _INLINE_CODE_RE.sub("", text)
    return text


def _collect_skill_field_refs(text: str, artifact_names: set[str]) -> dict[str, set[tuple[str, ...]]]:
    """Find <artifact>.<field.path> mentions in skill text. Returns {artifact: {paths}}.

    Strips inline code spans and fenced code blocks first — those typically
    contain Python module paths or function-call syntax that look like field
    references but aren't.
    """
    text = _strip_code_spans(text)
    found: dict[str, set[tuple[str, ...]]] = defaultdict(set)
    for match in _FIELD_REF_RE.finditer(text):
        head = match.group(1)
        tail = match.group(2)
        if head not in artifact_names:
            continue
        if head in _NON_ARTIFACT_PREFIXES:
            continue
        path = tuple(p for p in tail.lstrip(".").split(".") if p)
        if not path:
            continue
        # Drop file-path-shaped references like artifact.schema.json or artifact.yaml.
        if path[0] in _FILE_SUFFIX_FIRST_SEGMENTS:
            continue
        # Drop Python dict / object method calls like artifact.get(...) in pseudocode.
        if path[0] in _PYTHON_DICT_METHODS:
            continue
        found[head].add(path)
    return found


def _all_skill_files() -> list[Path]:
    return sorted(SKILLS_DIR.rglob("*.md"))


def _skill_text(relative_path: str) -> str:
    return (SKILLS_DIR / relative_path).read_text(encoding="utf-8")


def _skill_index_text() -> str:
    return _skill_text("INDEX.md")


def _normalize_skill_reference(reference: str) -> str:
    """Normalize manifest skill references to a skills/-relative markdown path."""
    normalized = reference.removeprefix("skills/")
    if not normalized.endswith(".md"):
        normalized = f"{normalized}.md"
    return normalized


def test_skill_index_lists_manifest_stage_directors_and_required_skills() -> None:
    """Every manifest-owned stage/director skill must be discoverable from INDEX.md."""
    index = _skill_index_text()
    missing: list[str] = []

    for pipeline_path in all_pipelines():
        manifest = load_pipeline(pipeline_path)
        references: set[str] = set()

        orchestration_skill = (manifest.get("orchestration") or {}).get("skill")
        if orchestration_skill:
            references.add(_normalize_skill_reference(orchestration_skill))

        for required in manifest.get("required_skills") or []:
            references.add(_normalize_skill_reference(required))

        for stage in manifest.get("stages") or []:
            stage_skill = stage.get("skill")
            if stage_skill:
                references.add(_normalize_skill_reference(stage_skill))

        for reference in sorted(references):
            if reference not in index:
                missing.append(f"{pipeline_path.name}: {reference}")

    assert not missing, (
        "skills/INDEX.md is missing manifest-owned director skills:\n  - "
        + "\n  - ".join(missing)
    )


def test_skill_index_lists_meta_skills() -> None:
    """Every meta skill should be listed in the index because routing starts there."""
    index = _skill_index_text()
    missing = [
        str(path.relative_to(SKILLS_DIR))
        for path in sorted((SKILLS_DIR / "meta").glob("*.md"))
        if str(path.relative_to(SKILLS_DIR)) not in index
    ]

    assert not missing, (
        "skills/INDEX.md is missing meta skills:\n  - " + "\n  - ".join(missing)
    )


@pytest.mark.parametrize(
    "skill_path", _all_skill_files(), ids=lambda p: str(p.relative_to(SKILLS_DIR))
)
def test_skill_field_references_resolve_in_schema(skill_path: Path) -> None:
    """Every <artifact>.<field> reference in a skill must resolve in the schema."""
    text = skill_path.read_text(encoding="utf-8")
    artifact_names = known_artifact_names()
    refs = _collect_skill_field_refs(text, artifact_names)
    if not refs:
        pytest.skip("no artifact field references")

    failures: list[str] = []
    for artifact, paths in sorted(refs.items()):
        schema = load_schema(artifact)
        if schema is None:
            # Reported by test_cross_stage_artifacts_have_schemas; don't double-fail.
            continue
        for path in sorted(paths):
            if not _path_is_valid(schema, path):
                failures.append(f"{artifact}.{'.'.join(path)}")

    assert not failures, (
        f"Skill {skill_path.relative_to(REPO)} references fields that are not in "
        f"their artifact schemas:\n  - " + "\n  - ".join(failures) + "\n"
        f"Either add the field to the schema, or correct the field path in the skill."
    )


# ---------------------------------------------------------------------------
# Check 4: embedded JSON examples validate against schema
# ---------------------------------------------------------------------------

# Match a heading/boldface line that names an artifact, followed by a fenced
# ```json block. Heuristic but conservative: only triggers when the author
# explicitly tags the example with one of the known artifact names.
#
# The (?!#+\s) negative lookahead in the lazy line-eater is critical: without
# it, the lazy match would happily span past intermediate headings and pair
# the FIRST heading in a file with the LAST json block, missing every other
# tagged example. The lookahead refuses to consume a line that begins another
# heading, so each (heading, ```json) pair resolves locally.
_TAGGED_JSON_RE = re.compile(
    r"(?:^|\n)(?P<header>#+\s+(?P<title>[^\n]+))\n+"
    r"(?:(?!#+\s)[^\n]*\n)*?"
    r"```json\s*\n(?P<body>.*?)\n```",
    re.DOTALL,
)

# Title-keyword → artifact-name. Conservative: only matches phrases that
# unambiguously refer to a single artifact's payload format.
_TITLE_TO_ARTIFACT = [
    ("intake brief", "intake_brief"),
    ("intelligence brief", "intelligence_brief"),
    ("production bible", "production_bible"),
    ("scene plan", "scene_plan"),
    ("asset manifest", "asset_manifest"),
    ("edit decisions", "edit_decisions"),
    ("render report", "render_report"),
    ("publish log", "publish_log"),
    ("script artifact", "script"),
    ("script format", "script"),
]


def _classify_example(title: str) -> str | None:
    lowered = title.lower()
    if not any(tag in lowered for tag in ("format", "schema", "artifact", "structure")):
        return None
    for keyword, artifact in _TITLE_TO_ARTIFACT:
        if keyword in lowered:
            return artifact
    return None


# Skill files whose tagged JSON examples are known to diverge from their
# artifact schemas. Each entry should be removed once the relevant schema is
# extended (or the skill example normalized) — until then, xfail keeps the
# linter green without losing the signal. Currently empty — all four
# previously-divergent ad-video examples were absorbed into their schemas.
KNOWN_SCHEMA_DIVERGED_EXAMPLES: set[str] = set()


@pytest.mark.parametrize(
    "skill_path", _all_skill_files(), ids=lambda p: str(p.relative_to(SKILLS_DIR))
)
def test_skill_json_examples_validate(skill_path: Path) -> None:
    """Fenced ```json examples explicitly tagged as a known artifact must validate."""
    rel = str(skill_path.relative_to(SKILLS_DIR))
    if rel in KNOWN_SCHEMA_DIVERGED_EXAMPLES:
        pytest.xfail(
            f"{rel}: known schema/example divergence — see "
            f"KNOWN_SCHEMA_DIVERGED_EXAMPLES comment for the schema-extension "
            f"backlog item that will let this test pass."
        )
    text = skill_path.read_text(encoding="utf-8")
    matches = list(_TAGGED_JSON_RE.finditer(text))
    if not matches:
        pytest.skip("no tagged JSON examples")

    failures: list[str] = []
    for match in matches:
        title = match.group("title").strip()
        artifact = _classify_example(title)
        if artifact is None:
            continue
        schema = load_schema(artifact)
        if schema is None:
            continue
        try:
            payload = json.loads(match.group("body"))
        except json.JSONDecodeError as e:
            failures.append(f"{title!r}: example is not valid JSON: {e}")
            continue
        try:
            jsonschema.validate(instance=payload, schema=schema)
        except jsonschema.ValidationError as e:
            failures.append(
                f"{title!r} (artifact={artifact}): {e.message} at "
                f"path {list(e.absolute_path)}"
            )

    assert not failures, (
        f"Skill {skill_path.relative_to(REPO)} contains tagged JSON examples that "
        f"don't validate against their artifact schemas:\n  - "
        + "\n  - ".join(failures)
    )


# ---------------------------------------------------------------------------
# Check 5: root skills stay aligned with the live media-runtime surface
# ---------------------------------------------------------------------------


def test_runtime_audit_skills_use_provider_menu_summary_for_preflight() -> None:
    """User-facing preflight skills must start from the compact provider menu."""
    files = [
        "INDEX.md",
        "meta/onboarding.md",
        "meta/video-reference-analyst.md",
        "pipelines/explainer/proposal-director.md",
        "pipelines/cinematic/proposal-director.md",
        "pipelines/animation/proposal-director.md",
    ]

    missing = [
        rel for rel in files
        if "provider_menu_summary()" not in _skill_text(rel)
    ]

    assert not missing, (
        "These skills still lack provider_menu_summary() as the primary preflight "
        f"entry point: {missing}. Raw support_envelope() is too large for "
        "user-facing routing and should only be a debugging/deep-inspection fallback."
    )


def test_runtime_audit_skills_cover_new_provider_tools_from_media_runtime_commit() -> None:
    """Layer 2 skills must name new providers added by the media-runtime commit."""
    expectations = {
        "INDEX.md": [
            "cosyvoice_tts",
            "wan_video_api",
            "wanx_image",
            "minimax_music",
            "qwen_asr",
            "subtitle_aligner",
        ],
        "creative/image-provider-usage.md": ["wanx_image", "DASHSCOPE_API_KEY"],
        "creative/video-gen-prompting.md": ["wan_video_api", "Wan 2.7"],
        "creative/music-gen-usage.md": ["minimax_music", "suno_music"],
        "core/whisperx.md": ["qwen_asr"],
        "core/subtitle-sync.md": ["subtitle_aligner", "ASS"],
    }

    missing: list[str] = []
    for rel, needles in expectations.items():
        text = _skill_text(rel)
        for needle in needles:
            if needle not in text:
                missing.append(f"{rel}: {needle}")

    assert not missing, (
        "Layer 2 skills are missing media-runtime provider/tool coverage:\n  - "
        + "\n  - ".join(missing)
    )


def test_remotion_skill_lists_every_scene_type_in_registry() -> None:
    """The core Remotion skill should not drift behind scene_type_registry.json."""
    registry = json.loads((REPO / "remotion-composer" / "scene_type_registry.json").read_text())
    scene_types = set(registry["scene_types"])
    text = _skill_text("core/remotion.md")

    missing = sorted(scene_type for scene_type in scene_types if scene_type not in text)

    assert not missing, (
        "skills/core/remotion.md does not mention registered scene types: "
        f"{missing}. Agents need this list before writing Remotion cuts."
    )
